export interface SeedVehicle {
  plate: string
  brand: string
  model: string
  version?: string
  color?: string
  category: 'citadine' | 'suv' | 'sportif'
  is_smart_fortwo?: boolean
  // Granular pricing
  price_day_week: number | null
  price_day_weekend: number | null
  price_weekend_full: number | null
  price_week: number | null
  km_included_day: number
  km_included_weekend: number
  km_included_week: number
  km_extra_price: number
  deposit_amount: number
  // Legacy columns (kept for backward compat with existing app code)
  daily_price: number | null
  weekly_price: number | null
  km_included_daily: number
  extra_km_price: number
  status: 'disponible'
  is_active: true
}

export const INITIAL_VEHICLES: SeedVehicle[] = [
  {
    plate: 'HK-347-GV',
    brand: 'BMW',
    model: 'i8',
    color: 'Blanc',
    category: 'sportif',
    price_day_week: 650,
    price_day_weekend: 700,
    price_weekend_full: 2000,
    price_week: null,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 10000,
    daily_price: 650,
    weekly_price: null,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
  {
    plate: 'B-122-RLS',
    brand: 'BMW',
    model: 'M135i',
    version: 'Bleu',
    color: 'Bleu',
    category: 'sportif',
    price_day_week: 250,
    price_day_weekend: 300,
    price_weekend_full: 800,
    price_week: 1500,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 5000,
    daily_price: 250,
    weekly_price: 1500,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
  {
    plate: 'GW-026-JD',
    brand: 'BMW',
    model: 'M135i',
    version: 'Noir',
    color: 'Noir',
    category: 'sportif',
    price_day_week: 250,
    price_day_weekend: 300,
    price_weekend_full: 800,
    price_week: 1500,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 5000,
    daily_price: 250,
    weekly_price: 1500,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
  {
    plate: 'GE-226-EZ',
    brand: 'BMW',
    model: 'Série 1',
    color: 'Blanc',
    category: 'citadine',
    price_day_week: 100,
    price_day_weekend: 150,
    price_weekend_full: 350,
    price_week: 550,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 2000,
    daily_price: 100,
    weekly_price: 550,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
  {
    plate: 'HK-294-MD',
    brand: 'Peugeot',
    model: '208',
    category: 'citadine',
    price_day_week: 80,
    price_day_weekend: 90,
    price_weekend_full: 250,
    price_week: 450,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 1500,
    daily_price: 80,
    weekly_price: 450,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
  {
    plate: 'GP-977-KZ',
    brand: 'DS',
    model: '3 Crossback',
    category: 'suv',
    price_day_week: 80,
    price_day_weekend: 90,
    price_weekend_full: 250,
    price_week: 450,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 1500,
    daily_price: 80,
    weekly_price: 450,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
  {
    plate: 'HF-760-LS',
    brand: 'Renault',
    model: 'Captur',
    category: 'citadine',
    price_day_week: 80,
    price_day_weekend: 90,
    price_weekend_full: 250,
    price_week: 450,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 1500,
    daily_price: 80,
    weekly_price: 450,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
  {
    plate: 'HA-974-JV',
    brand: 'Renault',
    model: 'Clio V Alpine',
    category: 'citadine',
    price_day_week: 80,
    price_day_weekend: 90,
    price_weekend_full: 250,
    price_week: 450,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 1500,
    daily_price: 80,
    weekly_price: 450,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
  {
    plate: 'FN-215-VR',
    brand: 'Citroën',
    model: 'C3',
    category: 'citadine',
    price_day_week: 50,
    price_day_weekend: 70,
    price_weekend_full: 200,
    price_week: 350,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 1000,
    daily_price: 50,
    weekly_price: 350,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
  {
    plate: 'DQ-314-CV',
    brand: 'Smart',
    model: 'Fortwo',
    category: 'citadine',
    is_smart_fortwo: true,
    price_day_week: 50,
    price_day_weekend: 70,
    price_weekend_full: 200,
    price_week: 350,
    km_included_day: 200,
    km_included_weekend: 600,
    km_included_week: 1200,
    km_extra_price: 2,
    deposit_amount: 500,
    daily_price: 50,
    weekly_price: 350,
    km_included_daily: 200,
    extra_km_price: 2,
    status: 'disponible',
    is_active: true,
  },
]
